import request from './request'

export const getCardKeyProjects = () => request.get('/card-keys')
export const getCardKeyMembers = () => request.get('/card-keys/members')
export const createCardKeyProject = (data) => request.post('/card-keys', data)
export const updateCardKeyProject = (id, data) => request.put(`/card-keys/${id}`, data)
export const deleteCardKeyProject = (id) => request.delete(`/card-keys/${id}`)
export const importCardKeys = (id, content) => request.post(`/card-keys/${id}/import`, { content })
export const getCardKeys = (id, params) => request.get(`/card-keys/${id}/keys`, { params })
export const claimCardKey = (id) => request.post(`/card-keys/${id}/claim`)
export const consumeCardKey = (projectId, keyId) => request.post(`/card-keys/${projectId}/keys/${keyId}/consume`)
export const releaseCardKey = (projectId, keyId) => request.post(`/card-keys/${projectId}/keys/${keyId}/release`)
export const markCardKeyInvalid = (projectId, keyId, remark) => request.post(`/card-keys/${projectId}/keys/${keyId}/invalid`, { remark })
export const updateCardKeyRemark = (projectId, keyId, remark) => request.put(`/card-keys/${projectId}/keys/${keyId}/remark`, { remark })
export const getCardKeyWorkReport = (projectId, params) => request.get(`/card-keys/${projectId}/work-report`, { params })
export const getClaimedEmail = (projectId) => request.get(`/card-keys/${projectId}/email`)
export const claimEmail = (projectId) => request.post(`/card-keys/${projectId}/email/claim`)
export const releaseEmail = (projectId) => request.post(`/card-keys/${projectId}/email/release`)
export const failEmail = (projectId, remark) => request.post(`/card-keys/${projectId}/email/fail`, { remark })
export const completeEmail = (projectId, data) => request.post(`/card-keys/${projectId}/email/complete`, data)
export const getClaimedEmailTotp = (projectId) => request.get(`/card-keys/${projectId}/email/totp`)
export const getCardKeyPlatforms = () => request.get('/card-keys/platforms')
export const createCardKeyPlatform = (data) => request.post('/card-keys/platforms', data)
export const updateCardKeyPlatform = (id, data) => request.put(`/card-keys/platforms/${id}`, data)
