"""Initial migration

Revision ID: c41ab6b0086e
Revises: 
Create Date: 2026-03-22 02:07:15.421892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41ab6b0086e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_proxies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('proxy_type', sa.Enum('socks5', 'http', 'https', name='proxy_type_enum'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_proxies_id'), 'monitor_proxies', ['id'], unique=False)
    op.create_table('monitor_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_interval', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_checks', sa.Integer(), nullable=False),
    sa.Column('request_timeout', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_settings_id'), 'monitor_settings', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('monitor_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('tiktok_id', sa.String(length=255), nullable=True),
    sa.Column('sec_uid', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monitor_interval', sa.Integer(), nullable=False),
    sa.Column('use_proxy', sa.Boolean(), nullable=False),
    sa.Column('proxy_id', sa.Integer(), nullable=True),
    sa.Column('enable_video_monitoring', sa.Boolean(), nullable=False),
    sa.Column('follower_count', sa.BigInteger(), nullable=False),
    sa.Column('following_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('video_count', sa.BigInteger(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_id'], ['monitor_proxies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_accounts_id'), 'monitor_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_monitor_accounts_project_id'), 'monitor_accounts', ['project_id'], unique=False)
    op.create_table('monitor_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('follower_count', sa.BigInteger(), nullable=False),
    sa.Column('following_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('video_count', sa.BigInteger(), nullable=False),
    sa.Column('check_status', sa.Enum('success', 'failed', name='check_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['monitor_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_history_account_id'), 'monitor_history', ['account_id'], unique=False)
    op.create_index(op.f('ix_monitor_history_checked_at'), 'monitor_history', ['checked_at'], unique=False)
    op.create_index(op.f('ix_monitor_history_id'), 'monitor_history', ['id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.String(length=1024), nullable=True),
    sa.Column('play_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('comment_count', sa.BigInteger(), nullable=False),
    sa.Column('share_count', sa.BigInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['monitor_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_account_id'), 'videos', ['account_id'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_index(op.f('ix_videos_video_id'), 'videos', ['video_id'], unique=True)
    op.create_table('video_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.BigInteger(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('comment_count', sa.BigInteger(), nullable=False),
    sa.Column('share_count', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_stats_id'), 'video_stats', ['id'], unique=False)
    op.create_index(op.f('ix_video_stats_recorded_at'), 'video_stats', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_video_stats_video_id'), 'video_stats', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_stats_video_id'), table_name='video_stats')
    op.drop_index(op.f('ix_video_stats_recorded_at'), table_name='video_stats')
    op.drop_index(op.f('ix_video_stats_id'), table_name='video_stats')
    op.drop_table('video_stats')
    op.drop_index(op.f('ix_videos_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_account_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_monitor_history_id'), table_name='monitor_history')
    op.drop_index(op.f('ix_monitor_history_checked_at'), table_name='monitor_history')
    op.drop_index(op.f('ix_monitor_history_account_id'), table_name='monitor_history')
    op.drop_table('monitor_history')
    op.drop_index(op.f('ix_monitor_accounts_project_id'), table_name='monitor_accounts')
    op.drop_index(op.f('ix_monitor_accounts_id'), table_name='monitor_accounts')
    op.drop_table('monitor_accounts')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_monitor_settings_id'), table_name='monitor_settings')
    op.drop_table('monitor_settings')
    op.drop_index(op.f('ix_monitor_proxies_id'), table_name='monitor_proxies')
    op.drop_table('monitor_proxies')
    # ### end Alembic commands ###
